DROP TABLE IF EXISTS roles;

CREATE TABLE roles
(
    id   INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) DEFAULT NULL,
    CONSTRAINT PK_Roles__id PRIMARY KEY (id)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
